/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event venues ParkApp operates around */
        get: operations["listVenues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/{venueId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Upcoming events at a venue */
        get: operations["listVenueEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/{venueId}/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spaces within 3 km of a venue, with availability for a time window
         * @description Poll this every few seconds for near real-time availability (no WebSockets).
         */
        get: operations["searchSpaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{spaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Space detail (no exact address) */
        get: operations["getSpace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{spaceId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reviews of a space, newest first */
        get: operations["listSpaceReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{spaceId}/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Price for a time window (computed by the server, never by the client) */
        get: operations["quoteSpace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in driver's bookings, newest first */
        get: operations["listMyBookings"];
        put?: never;
        /**
         * Hold a space while the driver pays (pre-booking expires at expiresAt)
         * @description Requires a complete account: personal data, at least one vehicle and a verified identity. Otherwise 403 with code profile_incomplete, vehicle_required or identity_required. 422 vehicle_not_supported when the vehicle type does not fit the space.
         */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{bookingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One of the signed-in driver's bookings */
        get: operations["getBooking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{bookingId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm after payment succeeded; reveals the exact address and access code */
        post: operations["confirmBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{bookingId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a booking (free until 10 minutes before it starts) */
        post: operations["cancelBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update language preference */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save the driver's personal data and accept the privacy notice */
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a vehicle */
        post: operations["addVehicle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/vehicles/{vehicleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a vehicle */
        delete: operations["removeVehicle"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start identity verification (INE and selfie through the identity provider)
         * @description Sets identityStatus to pending. The provider reports the result asynchronously (webhook); clients poll GET /api/me until it is verified or rejected.
         */
        post: operations["startIdentityVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
            version: string;
        };
        Problem: {
            /** @description Stable machine-readable code, for example space_unavailable */
            code: string;
            message: string;
        };
        LatLng: {
            lat: number;
            lng: number;
        };
        Venue: {
            id: string;
            name: string;
            /** @description Municipality or neighborhood */
            area: string;
            location: components["schemas"]["LatLng"];
            /** @description Operating radius in meters */
            radiusM: number;
        };
        VenueEvent: {
            id: string;
            venueId: string;
            title: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
        };
        /** @enum {string} */
        SpaceFeature: "covered" | "gate" | "camera" | "ev_charger" | "lit";
        SpaceSummary: {
            id: string;
            title: string;
            neighborhood: string;
            location: components["schemas"]["LatLng"];
            /** @description Meters to the requested venue */
            distanceM: number;
            priceCentsPerHour: number;
            rating: number;
            reviewCount: number;
            features: components["schemas"]["SpaceFeature"][];
            photoUrls: string[];
            /** @description Free for the whole requested window */
            available: boolean;
        };
        Dimensions: {
            lengthCm: number;
            widthCm: number;
            /** @description Clear height at the entrance */
            heightCm: number;
        };
        Space: components["schemas"]["SpaceSummary"] & {
            description: string;
            dimensions: components["schemas"]["Dimensions"];
            vehicleTypes: ("compact" | "sedan" | "suv" | "pickup")[];
            host: {
                displayName: string;
                verified: boolean;
                /** Format: date */
                memberSince: string;
            };
        };
        Review: {
            id: string;
            authorName: string;
            rating: number;
            comment: string;
            /** Format: date-time */
            createdAt: string;
        };
        Quote: {
            minutes: number;
            subtotalCents: number;
            serviceFeeCents: number;
            totalCents: number;
        };
        BookingCreate: {
            spaceId: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** @description One of the driver's registered vehicles */
            vehicleId: string;
        };
        /** @enum {string} */
        BookingStatus: "pending_payment" | "confirmed" | "cancelled" | "expired" | "completed";
        Booking: {
            id: string;
            status: components["schemas"]["BookingStatus"];
            space: {
                id: string;
                title: string;
                neighborhood: string;
                /** @description Exact address. Only present once status is confirmed or completed */
                address: string | null;
                photoUrl: string | null;
                /** @description Where to park inside the property, shown after confirmation */
                spotLabel: string | null;
            };
            venueName: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            vehicle: components["schemas"]["Vehicle"];
            subtotalCents: number;
            serviceFeeCents: number;
            totalCents: number;
            /**
             * Format: date-time
             * @description When an unpaid pre-booking is released
             */
            expiresAt: string | null;
            /** @description Shown once the booking is confirmed */
            accessCode: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        /** @enum {string} */
        VehicleType: "compact" | "sedan" | "suv" | "pickup";
        Vehicle: {
            id: string;
            plate: string;
            make: string;
            model: string;
            color: string;
            type: components["schemas"]["VehicleType"];
        };
        VehicleInput: {
            plate: string;
            make: string;
            model: string;
            color: string;
            type: components["schemas"]["VehicleType"];
        };
        ProfileInput: {
            firstName: string;
            lastName: string;
            /**
             * Format: date
             * @description Must be at least 18 years ago
             */
            birthDate: string;
            /** Format: email */
            email: string;
            /** @description Must be true. Records consent to the privacy notice */
            acceptPrivacy: boolean;
        };
        /** @enum {string} */
        IdentityStatus: "not_started" | "pending" | "verified" | "rejected";
        Me: {
            id: string;
            phone: string | null;
            email: string | null;
            firstName: string | null;
            lastName: string | null;
            /** Format: date */
            birthDate: string | null;
            /** @enum {string} */
            language: "es-MX" | "en";
            /** Format: date-time */
            privacyAcceptedAt: string | null;
            identityStatus: components["schemas"]["IdentityStatus"];
            vehicles: components["schemas"]["Vehicle"][];
        };
    };
    responses: {
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description The account is not ready for this action */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Invalid input */
        Invalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listVenues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Venues */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Venue"][];
                    };
                };
            };
        };
    };
    listVenueEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upcoming events, soonest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["VenueEvent"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    searchSpaces: {
        parameters: {
            query: {
                startsAt: string;
                endsAt: string;
            };
            header?: never;
            path: {
                venueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Spaces sorted by distance to the venue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["SpaceSummary"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["Invalid"];
        };
    };
    getSpace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Space */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Space"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listSpaceReviews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reviews */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Review"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    quoteSpace: {
        parameters: {
            query: {
                startsAt: string;
                endsAt: string;
            };
            header?: never;
            path: {
                spaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quote */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quote"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["Invalid"];
        };
    };
    listMyBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Booking"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description Held. Status is pending_payment */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The space is already booked for part of that window */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["Invalid"];
        };
    };
    getBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    confirmBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    paymentIntentId: string;
                };
            };
        };
        responses: {
            /** @description Confirmed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The pre-booking expired or was cancelled */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Too late to cancel, or already cancelled */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    language?: "es-MX" | "en";
                };
            };
        };
        responses: {
            /** @description Profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInput"];
            };
        };
        responses: {
            /** @description Updated account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Invalid"];
        };
    };
    addVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleInput"];
            };
        };
        responses: {
            /** @description Updated account */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Invalid"];
        };
    };
    removeVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    startIdentityVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
